### ISSUE TITLE
RSECon24 website accesibility

### ISSUE THREAD

**Issue by stefpiatek** [socrse/edia#21]
Using this issue to track feedback on https://rsecon24.society-rse.org/

TODO:

- [x] https://www.a11yproject.com/checklist/
- [x] screen reader testing

Feedback

- [x] lighthouse [mobile](https://pagespeed.web.dev/analysis/https-rsecon24-society-rse-org/ljxuba00fl?form_factor=mobile) and [desktop](https://pagespeed.web.dev/analysis/https-rsecon24-society-rse-org/ljxuba00fl?form_factor=desktop) assessments
- [x] [wave](https://wave.webaim.org/report#/https://rsecon24.society-rse.org)

**Comment by davehorsfall** [comment]
Thanks @stefpiatek. @lifan0127, do you want to review some of the feedback from these tool, and arrange to meet and discuss in more details?

**Comment by lifan0127** [comment]
Sure, Dave. I will post the test results here and we can also discuss.

**Comment by lifan0127** [comment]
Hi Dave, I have made several changes to address the WAVE accessibility errors and alerts for the home page. We still have some remaining alerts, please advise the actions needed, if any.

https://github.com/socrse/rsecon24-website/pull/87/files

![image](https://github.com/socrse/edia/assets/7218193/c5e73093-1adb-44db-ba4b-cc5e30750653)

**Comment by elichad** [comment]
I had a (nonexhaustive) go navigating the site with a screen reader and found the following issues:

- can't expand the navbar items with keyboard (only mouse), see https://www.w3.org/WAI/tutorials/menus/flyout/ for suggestions on how to fix this
- programme is hard to navigate with a screen reader as all the event blocks are in a single table row (I was expecting each time slot to be a row, like in this [accessibility conference schedule](https://www.deque.com/axe-con/schedule/) for example)
- names of short sessions can become hidden when zoomed, see image below (I wouldn't have known that some of them said Keynote if I hadn't heard it in the screen reader! My screen is at 125% zoom.)

Screenshot of RSECon23 programme and a search for "keynote". Some sessions have a small highlighted bar showing where the word "keynote" is present but not visible.
![described in text](https://github.com/socrse/edia/assets/20683271/97642a85-64f5-483d-8168-8bdf168ab1ba)

**Comment by lifan0127** [comment]
> can't expand the navbar items with keyboard (only mouse), see https://www.w3.org/WAI/tutorials/menus/flyout/ for suggestions on how to fix this

This should be working now. Please give it a try.

**Comment by lifan0127** [comment]
> programme is hard to navigate with a screen reader as all the event blocks are in a single table row (I was expecting each time slot to be a row, like in this [accessibility conference schedule](https://www.deque.com/axe-con/schedule/) for example)

The programme calendar uses the [calendar event](https://around.createx.studio/components/calendar.html#calendar) widget provided by the website template. Internally it is based on the [FullCalendar library](https://fullcalendar.io/). As such, we are unable to change its overall HTML structure.

**Comment by lifan0127** [comment]
> names of short sessions can become hidden when zoomed, see image below (I wouldn't have known that some of them said Keynote if I hadn't heard it in the screen reader! My screen is at 125% zoom.)

The calendar height has been made adaptive based on zoom level and window width. Please give it a try.

**Comment by elichad** [comment]
Thanks for the quick updates! The navbar works better now, but the calendar has changed slightly but still isn't right.

![Screenshot of RSECon programme with some event names mostly hidden](https://github.com/socrse/edia/assets/20683271/dd921a9d-9091-492f-8233-066670b3e110)

**Comment by lifan0127** [comment]
What is your browser? And the width of the browser window?

**Comment by elichad** [comment]
Firefox, and my screen is 1920x1080 but at 125% zoom I think that's equivalent to 1536x864.

It's also the same problem on my mobile phone, again with Firefox (I think around 400 width, though I can't replicate it on my computer with Firefox's Responsive Design Mode)

![Screenshot of RSECon Tuesday programme on mobile, with event names hidden](https://github.com/socrse/edia/assets/20683271/12f27cb4-7221-46db-b3bc-1fb488446e5c)

**Comment by lifan0127** [comment]
Thanks! Let me know if it works better now.

The calendar must be rendered at a fixed aspect ratio, with the width being the full width of the browser window. I have added some customization to calculate the desired aspect ratio based on the window size and the zoom level. But it is hard to get right for all the scenarios.

**Comment by elichad** [comment]
It looks fine on my computer screen now, but not fixed on my mobile screen yet.

**Comment by stefpiatek** [comment]
Great to see things moving in the right direction, is there anything that the EDIA working group can do to help at this point?

**Comment by lifan0127** [comment]
A more mobile-friendly list view has been added for the programme page.

![Screenshot_20240411-115343.png](https://github.com/socrse/edia/assets/7218193/b8bf2556-46eb-47e8-ade2-a4decde25807)

**Comment by stefpiatek** [comment]
@lifan0127 Looking great, thanks! It looks like there's still some contrast errors from the [wave report](https://wave.webaim.org/report#/https://rsecon24.society-rse.org), messes with the colour scheme a bit but would you be able to fix those up? 🙏 

Once that's resolve the EDIA working group is happy to close this issue 🎉

**Comment by lifan0127** [comment]
The contrast has been increased to resolve the errors:

![image](https://github.com/socrse/edia/assets/7218193/e150d42e-2254-4541-a260-6c3b6e7b6af3)

**Comment by stefpiatek** [comment]
Great, appreciate it @lifan0127 ❤️! @elichad Anything else that you'd like to have resolved from your side (a couple of alerts remaining)?

**Comment by elichad** [comment]
I don't have anything else - if I come across more issues while using the site for registration/abstract submission/etc, I'll let you know
